# Generated by Django 4.2.4 on 2023-11-10 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('firm_name', models.CharField(max_length=50)),
                ('biography', models.TextField(blank=True, null=True)),
                ('phone_number', models.IntegerField()),
                ('web_adres', models.TextField(blank=True, null=True)),
                ('profile_pic1', models.ImageField(blank=True, upload_to='profile_pics')),
                ('profile_pic2', models.ImageField(blank=True, upload_to='profile_pics')),
                ('profile_pic3', models.ImageField(blank=True, upload_to='profile_pics')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='kayıt tarihi')),
                ('instagram', models.TextField(max_length=50)),
                ('facebook', models.TextField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
