# Generated by Django 4.2.4 on 2023-11-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('egitim', 'Eğitim'), ('saglik', 'Sağlık'), ('insaat', 'İnşaat'), ('gida', 'Gıda'), ('ulasim', 'Ulaşım'), ('diger', 'Diğer')], default='sinoplu', max_length=20, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(choices=[('istanbul', 'İstanbul'), ('sinop', 'Sinop'), ('ankara', 'Ankara')], default='sinope', max_length=20, verbose_name='Şehir'),
        ),
    ]
