# Generated by Django 4.2.4 on 2023-12-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paid_status',
            field=models.CharField(choices=[('e', 'odendi'), ('h', 'odenmedi')], default='h', max_length=10),
        ),
    ]
