# Generated by Django 4.2.4 on 2023-12-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_paid_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['register_date'], 'verbose_name_plural': 'sinoplu listesi'},
        ),
    ]
