# Generated by Django 4.2.4 on 2024-01-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('Eğitim', 'egitim'), ('Sağlık', 'saglik'), ('İnşaat', 'insaat '), ('Gıda', 'gida'), ('Ulaşım', 'ulasim'), ('Diğer', 'diger')], default='sinoplu', max_length=20, verbose_name='Kategori'),
        ),
    ]
