# Generated by Django 4.2.4 on 2024-01-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='firm_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
