# Generated by Django 4.2.4 on 2024-01-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='twitter',
            field=models.URLField(max_length=50, null=True),
        ),
    ]
