# Generated by Django 4.2.4 on 2024-01-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
