# Generated by Django 4.2.4 on 2024-02-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Mesajlar'},
        ),
    ]
