# Generated by Django 4.2.4 on 2024-02-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_userprofile_category_alter_userprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Yaş'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Biyografi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firm_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Firma Adı'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Soyadı'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='web_adres',
            field=models.URLField(blank=True, null=True, verbose_name='Web Adresi'),
        ),
    ]
