# Generated by Django 4.2.4 on 2024-02-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_userprofile_age_alter_userprofile_biography_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='guess_email',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('egitim', 'Eğitim'), ('saglik', 'Sağlıkk'), ('insaat', 'İnşaat '), ('gida', 'Gıda'), ('ulasimm', 'Ulaşımm'), ('diger', 'Diğer')], default='sinoplu', max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(choices=[('istanbul', 'İstanbul'), ('sinop', 'Sinop'), ('ankara', 'Ankara')], default='sinope', max_length=20, verbose_name='Yaşadığınız Şehir'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Adınız'),
        ),
    ]
