# Generated by Django 4.2.4 on 2024-02-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_userprofile_age_alter_userprofile_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('egitim', 'Eğitim'), ('saglik', 'Sağlık'), ('insaat', 'İnşaat '), ('gida', 'Gıda'), ('ulasim', 'Ulaşım'), ('diger', 'Diğer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(choices=[('istanbul', 'İstanbul'), ('sinop', 'Sinop'), ('ankara', 'Ankara')], default='Sinop', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firm_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
