# Generated by Django 4.2.4 on 2024-02-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_userprofile_category_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('egitim', 'Eğitim'), ('saglik', 'Sağlık'), ('insaat', 'İnşaat '), ('gida', 'Gıda'), ('ulasim', 'Ulaşım'), ('diger', 'Diğer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(choices=[('istanbul', 'İstanbul'), ('sinop', 'Sinop'), ('ankara', 'Ankara')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='web_adres',
            field=models.URLField(blank=True, default='http://www.sinopluyuz.com', null=True),
        ),
    ]
