# Generated by Django 4.2.4 on 2024-02-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_userprofile_age_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='web_adres',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
