# Generated by Django 4.2.4 on 2024-02-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_userprofile_web_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pinterest',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtube',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
