# Generated by Django 4.2.4 on 2024-02-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_userprofile_linkedin_userprofile_pinterest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='firm_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
