# Generated by Django 4.2.4 on 2024-03-04 17:35

from django.db import migrations, models
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_userprofile_firm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, scale=0.9, size=[960, 720], upload_to=users.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='paid_status',
            field=models.CharField(choices=[('e', 'odendi'), ('h', 'odenmedi')], default='e', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, scale=0.9, size=[960, 720], upload_to=users.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, scale=0.9, size=[960, 720], upload_to=users.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, scale=0.9, size=[960, 720], upload_to=users.models.user_directory_path),
        ),
    ]
