# Generated by Django 4.2.4 on 2024-03-04 17:42

from django.db import migrations
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_userprofile_avatar_alter_userprofile_paid_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='assets/img/user-man.jpg', force_format='JPEG', keep_meta=True, null=True, quality=90, scale=0.9, size=[150, 150], upload_to=users.models.user_directory_path),
        ),
    ]
