# Generated by Django 4.2.4 on 2024-03-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_userprofile_profile_pic1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pinterest',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='youtube',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
