# Generated by Django 4.2.4 on 2024-03-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_userprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='guess_number',
            field=models.IntegerField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
