# Generated by Django 4.2.4 on 2024-03-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_contact_guess_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name_plural': 'Like sayısı'},
        ),
        migrations.AlterModelOptions(
            name='profileview',
            options={'verbose_name_plural': 'Görülme sayısı'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='guess_number',
            field=models.IntegerField(),
        ),
    ]
