# Generated by Django 4.1.1 on 2024-04-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_like_options_alter_profileview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
