# Generated by Django 4.1.1 on 2024-04-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_userprofile_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
