# Generated by Django 4.1.1 on 2024-04-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_userprofile_biography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user_like',
            new_name='view_or_like',
        ),
        migrations.RenameField(
            model_name='profileview',
            old_name='user_view',
            new_name='view_or_like',
        ),
    ]
