# Generated by Django 4.1.1 on 2024-04-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_rename_user_like_like_view_or_like_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='view_or_like',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='profileview',
            old_name='view_or_like',
            new_name='post',
        ),
    ]
