# Generated by Django 4.1.1 on 2024-04-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_rename_view_or_like_like_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='view_and_like',
        ),
        migrations.RenameField(
            model_name='profileview',
            old_name='post',
            new_name='view_and_like',
        ),
    ]
