# Generated by Django 4.1.1 on 2024-05-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_rename_post_like_view_and_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileview',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='my_checkbox',
            field=models.BooleanField(default='True'),
        ),
    ]
