# Generated by Django 4.1.1 on 2024-05-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_userprofile_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(default='İnternet', max_length=255),
        ),
    ]
