# Generated by Django 4.1.1 on 2024-05-12 21:39

from django.db import migrations
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_userprofile_profile_pic1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='assets/img/user-man.jpg', force_format='JPEG', keep_meta=True, quality=90, scale=0.9, size=[150, 150], upload_to=users.models.user_directory_path),
        ),
    ]
